<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Routing\RouteMatchInterface;

include_once('DrupalTWSparql.inc');

function twsparql_entity_delete(EntityInterface $entity) {
}

function twsparql_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
	$build['body'][0]["#text"] = TWSparql::$engine->render( 1, $build['body'][0]["#text"] );
}

function twsparql_entity_update(EntityInterface $entity) {
}

function twsparql_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.twsparql':
      $output = '<p>' . t('The TWSparql module allows a user to define a &lt;sparql&gt; tag that invokes a sparql query against a defined endpoint,
                 applying an xsl translation of the xml response and displaying the result within the Drupal page') . '</p>';
      return $output;
  }
}

function twsparql_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'core/jquery';
}
